# My First Useful Make file :)

#gcc    -c -o main.o main.c
#gcc    -c -o school.o school.c
#gcc main.o school.o -o school

CC=gcc
SRC=main.c school.c
OBJ=main.o school.o

.PHONY: clean

%.o: %.c
	$(CC) -c -o $@ $<

school: $(OBJ)
	$(CC) -o $@ $^
clean:
	rm -f *.o school
